apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: express-middleware-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: express-middleware  
    spec:     # pod spec                  
      containers: 
      - name: express-middleware 
        image: gcr.io/phineasrt/express-middleware-image:v1 # image we pushed
        ports:
        - containerPort: 3000
